### ISSUE TITLE
Coinbase pro QR code - No grids found

### ISSUE THREAD

**Issue by gr211** [WanzenBug/rqrr#6] opened 2021-02-01 22:23 UTC
Failing to parse pro.coinbase.com's generated QR code.

Not sure how to create a test case to expose problem. Can't really paste my QR here.

Current implementation of `rqrr` in project is here [edit_account_window.rs](https://github.com/grumlimited/authenticator-rs/blob/master/src/ui/edit_account_window.rs#L159). It works fine with a lot of QR png images I have tried it with. This is so far the only QR code it could not "parse".

Please also note that the very same QR png image is decoded just fine using [zxing](https://zxing.org/w/decode).

Please let me know if there is any way I can help.

**Comment by WanzenBug** [comment] 2021-02-02 19:30
Unfortunatly, without an example to reliably reproduce this I don't think there is anything I can do :/

If you are really motivated, you could try changing the test here: https://github.com/WanzenBug/rqrr/blob/4ec8b4235c301359c310ac5a1b68fda584846edd/src/detect.rs#L522
It should find the 3 "capstones", i.e. the 3 corner patterns

**Comment by gr211** [comment] 2021-02-04 10:31
Hi,
So I tried the following

```
#[test]
fn test_cap() {
        let caps = load_and_find(include_bytes!("canvas.png"));
        assert_eq!(1, caps.len());
}
```

with `canvas.png` being the same png file that "passes" with zxing but not rqrr. I left the assertion as-is. The result is

```
test detect::tests::test_cap ... FAILED

failures:

---- detect::tests::test_cap stdout ----
thread 'detect::tests::test_cap' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/detect.rs:523:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it's not `1` or `3`, but a fierce `2` coming back.

I'm not very familiar with QR codes terminology. I am correct in thinking the "capstones" are the big squares in the top-left, top-right and bottom-left corners ?
If yes, then `"canvas.png"` has got them 3 in those positions.

**Comment by gr211** [comment] 2021-02-04 10:56
How could I send you an obfuscated version of the QR code in question ?

**Comment by WanzenBug** [comment] 2021-02-04 11:04
Yeah, the "capstones" are the black squares with black+white border. It needs all 3 to recognize a QR code. 

You could remove everything but the 3 squares + border (paint them white or make it transparent or whatever).

**Comment by gr211** [comment] 2021-02-04 11:46
I tried emailing it to you via (what i think is) your github email address. Did you get it ?

**Comment by WanzenBug** [comment] 2021-02-04 11:50
Not yet. My mail address is in my profile: `moritz@wanzenbug.xyz`

**Comment by WanzenBug** [comment] 2021-02-04 12:00
got it now. I'll take a look when I find the time. Can't promise any specific date :wink:

**Comment by WanzenBug** [comment] 2021-02-04 17:54
Well, thanks to the example it wasn't that hard to find. Basically the problem was that one capstone was right on right edge of the image. The image scanner only triggers after observing a specific black-white pattern (b-w-b-w-b-w). This is a problem at the right edge if the capstone, as the scanner cant find the last black-white transition (because the image stops with black). Fixed in https://github.com/WanzenBug/rqrr/commit/706bbad6e7df35ef9ef9a949d22b5ecfd3363127#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

Pushed a new 0.3.1 release

**Comment by gr211** [comment] 2021-02-04 21:55
Thanls @WanzenBug

**Closed** 2021-02-05 07:31 UTC
Labels: bug
